# Generated by Django 6.0.8 on 2026-10-05 18:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_code", models.CharField(max_length=64, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("middle_initial", models.CharField(blank=True, max_length=10)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "faculty_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full time"),
                            ("PART_TIME", "Part time"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "max_teaching_load",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "faculty",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_code", models.CharField(max_length=32, unique=True)),
                (
                    "room_type",
                    models.CharField(
                        choices=[("LECTURE", "Lecture"), ("LAB", "Laboratory")],
                        max_length=32,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "room",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_code", models.CharField(max_length=64, unique=True)),
                ("subject_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "subject",
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program_code", models.CharField(max_length=32, unique=True)),
                ("program_name", models.CharField(max_length=255)),
                (
                    "max_year_level",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "program",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("max_year_level__gte", 1)),
                        name="program_year_positive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProgramSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_level",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("units", models.PositiveSmallIntegerField()),
                ("lecture_periods", models.PositiveSmallIntegerField()),
                ("lab_periods", models.PositiveSmallIntegerField()),
                ("lecture_meetings_per_week", models.PositiveSmallIntegerField()),
                ("lab_meetings_per_week", models.PositiveSmallIntegerField()),
                (
                    "lecture_room_type",
                    models.CharField(
                        choices=[("LECTURE", "Lecture"), ("LAB", "Laboratory")],
                        default="LECTURE",
                        max_length=32,
                    ),
                ),
                (
                    "lab_room_type",
                    models.CharField(
                        choices=[("LECTURE", "Lecture"), ("LAB", "Laboratory")],
                        default="LAB",
                        max_length=32,
                    ),
                ),
                ("is_elective", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="master_data.program",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="master_data.subject",
                    ),
                ),
            ],
            options={
                "db_table": "program_subject",
            },
        ),
        migrations.CreateModel(
            name="FacultyTeachingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teaching_rule",
                    models.CharField(
                        choices=[
                            ("CANNOT", "CANNOT"),
                            ("CAN", "CAN"),
                            ("MUST_TEACH", "MUST_TEACH"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master_data.faculty",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="master_data.subject",
                    ),
                ),
            ],
            options={
                "db_table": "faculty_teaching_rule",
            },
        ),
        migrations.CreateModel(
            name="SubjectAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=64, unique=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master_data.subject",
                    ),
                ),
            ],
            options={
                "db_table": "subject_alias",
            },
        ),
        migrations.CreateModel(
            name="BlockSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_level",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("section_code", models.CharField(max_length=32)),
                (
                    "student_count",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="master_data.program",
                    ),
                ),
            ],
            options={
                "db_table": "block_section",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("program", "year_level", "section_code"),
                        name="unique_block",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("year_level__gte", 1)),
                        name="block_year_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProgramSubjectPrerequisite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prerequisite_program_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dependents",
                        to="master_data.programsubject",
                    ),
                ),
                (
                    "program_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisites",
                        to="master_data.programsubject",
                    ),
                ),
            ],
            options={
                "db_table": "program_subject_prerequisite",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("program_subject", "prerequisite_program_subject"),
                        name="unique_prerequisite",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="programsubject",
            constraint=models.UniqueConstraint(
                fields=("program", "subject"), name="unique_program_subject"
            ),
        ),
        migrations.AddConstraint(
            model_name="programsubject",
            constraint=models.CheckConstraint(
                condition=models.Q(("year_level__gte", 1)),
                name="curriculum_year_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="facultyteachingrule",
            constraint=models.UniqueConstraint(
                fields=("faculty", "subject"), name="unique_faculty_rule"
            ),
        ),
        migrations.AddConstraint(
            model_name="facultyteachingrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("teaching_rule__in", ["CANNOT", "CAN", "MUST_TEACH"])),
                name="categorical_rule",
            ),
        ),
    ]
