# Generated by Django 6.0.8 on 2026-10-05 18:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.validation


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("master_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_enrollment", models.PositiveIntegerField()),
                (
                    "failure_adjustment",
                    models.DecimalField(decimal_places=6, max_digits=14),
                ),
                ("forecasted_students", models.PositiveIntegerField()),
                ("required_sections", models.PositiveIntegerField()),
                ("forecast_method", models.CharField(max_length=32)),
                ("computation", models.JSONField(default=dict)),
                (
                    "program_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="master_data.programsubject",
                    ),
                ),
            ],
            options={
                "db_table": "forecast_result",
            },
        ),
        migrations.CreateModel(
            name="CourseOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_number",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "expected_students",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[("LECTURE", "Lecture"), ("LAB", "Lab")], max_length=8
                    ),
                ),
                (
                    "duration_periods",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "meetings_per_week",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "program_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="master_data.programsubject",
                    ),
                ),
                (
                    "forecast_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offerings",
                        to="forecasting.forecastresult",
                    ),
                ),
            ],
            options={
                "db_table": "course_offering",
            },
        ),
        migrations.CreateModel(
            name="ForecastRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(max_length=9, validators=[apps.core.validation.academic_year]),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("FINALIZED", "Finalized")],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "section_capacity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="forecasts_finalized",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="forecasts_generated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "forecast_run",
            },
        ),
        migrations.AddField(
            model_name="forecastresult",
            name="forecast_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="forecasting.forecastrun",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(max_length=9, validators=[apps.core.validation.academic_year]),
                ),
                ("enrollment_count", models.PositiveIntegerField()),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="master_data.program",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="master_data.subject",
                    ),
                ),
            ],
            options={
                "db_table": "historical_enrollment",
            },
        ),
        migrations.CreateModel(
            name="CourseOfferingBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="master_data.blocksection",
                    ),
                ),
                (
                    "course_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_links",
                        to="forecasting.courseoffering",
                    ),
                ),
            ],
            options={
                "db_table": "course_offering_block",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("course_offering", "block_section"),
                        name="unique_offering_block",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="courseoffering",
            constraint=models.UniqueConstraint(
                fields=("forecast_result", "section_number", "component_type"),
                name="unique_offering",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastresult",
            constraint=models.UniqueConstraint(
                fields=("forecast_run", "program_subject"),
                name="unique_forecast_result",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalenrollment",
            constraint=models.UniqueConstraint(
                fields=("academic_year", "program", "subject"), name="unique_history"
            ),
        ),
    ]
