# Generated by Django 6.0.8 on 2026-10-05 18:16

import django.db.models.deletion
from django.db import migrations, models

import apps.core.validation


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("forecasting", "0001_initial"),
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(max_length=9, validators=[apps.core.validation.academic_year]),
                ),
                ("solver_name", models.CharField(default="HiGHS", max_length=32)),
                ("status", models.CharField(default="QUEUED", max_length=32)),
                ("objective_value", models.FloatField(blank=True, null=True)),
                ("best_bound", models.FloatField(blank=True, null=True)),
                ("mip_gap", models.FloatField(blank=True, null=True)),
                ("nodes_explored", models.PositiveIntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("elapsed_seconds", models.FloatField(blank=True, null=True)),
                ("scenario_snapshot", models.JSONField(default=dict)),
                ("diagnostic", models.TextField(blank=True)),
            ],
            options={
                "db_table": "schedule_run",
            },
        ),
        migrations.CreateModel(
            name="ScheduleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meeting_number", models.PositiveSmallIntegerField()),
                ("day_index", models.PositiveSmallIntegerField()),
                ("start_period", models.PositiveSmallIntegerField()),
                ("duration_periods", models.PositiveSmallIntegerField()),
                (
                    "course_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="forecasting.courseoffering",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="master_data.faculty",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="master_data.room",
                    ),
                ),
                (
                    "schedule_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="scheduling.schedulerun",
                    ),
                ),
            ],
            options={
                "db_table": "schedule_assignment",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("schedule_run", "course_offering", "meeting_number"),
                        name="unique_assignment",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SolverMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence_number", models.PositiveIntegerField()),
                ("elapsed_seconds", models.FloatField()),
                ("objective_value", models.FloatField(blank=True, null=True)),
                ("best_bound", models.FloatField(blank=True, null=True)),
                ("mip_gap", models.FloatField(blank=True, null=True)),
                ("nodes_explored", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "schedule_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="scheduling.schedulerun",
                    ),
                ),
            ],
            options={
                "db_table": "solver_metric",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("schedule_run", "sequence_number"), name="unique_metric"
                    )
                ],
            },
        ),
    ]
